server:
  port: 8001
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/personalweb
    username: zhush
    password: NtMS7M72tS48bpwM
  thymeleaf:
    prefix: classpath:/templates/
    enabled: true
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false

mybatis:
  mapper-locations:
    - classpath:mybatis/*.xml